name: hello_world_dart
publish_to: none # let's not accidentally publish this to pub.dartlang.org
description: Hello world server example in Dart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  shelf: ^0.7.9